package naberius.init;

import java.util.ArrayList;
import java.util.List;

import naberius.config.NaberiusConfig;
import naberius.handler.MaterialHandler;
import naberius.item.ItemBackpack;
import naberius.item.ItemCore;
import naberius.item.ItemDemonicStone;
import naberius.item.armor.ItemAdamantiumArmor;
import naberius.item.armor.ItemBronzeArmor;
import naberius.item.armor.ItemDemonicArmor;
import naberius.item.armor.ItemSiriumArmor;
import naberius.item.armor.ItemSteelArmor;
import naberius.item.drops.ItemDemonEye;
import naberius.item.drops.ItemDemonFlesh;
import naberius.item.drops.ItemDemonPearl;
import naberius.item.drops.ItemHolyWater;
import naberius.item.manual.ItemManual;
import naberius.item.material.ItemIngot;
import naberius.item.material.ItemNugget;
import naberius.item.material.ItemPlate;
import naberius.item.porter.ItemCleansedPorter;
import naberius.item.porter.ItemCorruptedPorter;
import naberius.item.tool.ItemToolAoE;
import naberius.item.tool.ItemToolAxe;
import naberius.item.tool.ItemToolHammer;
import naberius.item.tool.ItemToolHoe;
import naberius.item.tool.ItemToolPickaxe;
import naberius.item.tool.ItemToolShovel;
import naberius.item.tool.ItemToolSword;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ItemRegistry {

	public static List<Item> ITEMS = new ArrayList();
	public static ItemIngot INGOT = new ItemIngot();
	public static ItemCore CORE = new ItemCore();
	public static ItemNugget NUGGET = new ItemNugget();
	public static ItemPlate PLATE = new ItemPlate();
	public static ItemDemonFlesh DEMON_FLESH = new ItemDemonFlesh();
	public static ItemManual MANUAL = new ItemManual();
	public static ItemDemonicStone DEMONIC_STONE = new ItemDemonicStone();
	public static ItemCleansedPorter CLEANSED_DEMON_PORTER = new ItemCleansedPorter();
	public static ItemCorruptedPorter CORRUPTED_DEMON_PORTER = new ItemCorruptedPorter();
	public static ItemBackpack BACKPACK = new ItemBackpack();
	public static ItemHolyWater HOLY_WATER = new ItemHolyWater();
	public static ItemDemonPearl DEMON_PEARL = new ItemDemonPearl();
	public static ItemDemonEye DEMON_EYE = new ItemDemonEye();
	public static ItemToolAxe TITANIUM_AXE = new ItemToolAxe(MaterialHandler.Tools.Titanium, "titanium_axe", null, -1);
	public static ItemToolAxe VIBRANIUM_AXE = new ItemToolAxe(MaterialHandler.Tools.Vibranium, "vibranium_axe", null, -1);
	public static ItemToolAxe ADAMANTIUM_AXE = new ItemToolAxe(MaterialHandler.Tools.Adamantium, "adamantium_axe", null, -1);
	public static ItemToolAxe SIRIUM_AXE = new ItemToolAxe(MaterialHandler.Tools.Sirium, "sirium_axe", null, -1);
	public static ItemToolAxe DEMONIC_AXE = new ItemToolAxe(MaterialHandler.Tools.Demonic, "demonic_axe", null, -1);
	public static ItemToolAxe STEEL_AXE = new ItemToolAxe(MaterialHandler.Tools.Steel, "steel_axe", null, -1);
	public static ItemToolAxe BRONZE_AXE = new ItemToolAxe(MaterialHandler.Tools.Bronze, "bronze_axe", null, -1);
	public static ItemToolAxe SILVER_AXE = new ItemToolAxe(MaterialHandler.Tools.Silver, "silver_axe", null, -1);
	public static ItemToolHoe TITANIUM_HOE = new ItemToolHoe(MaterialHandler.Tools.Titanium, "titanium_hoe");
	public static ItemToolHoe VIBRANIUM_HOE = new ItemToolHoe(MaterialHandler.Tools.Vibranium, "vibranium_hoe");
	public static ItemToolHoe ADAMANTIUM_HOE = new ItemToolHoe(MaterialHandler.Tools.Adamantium, "adamantium_hoe");
	public static ItemToolHoe SIRIUM_HOE = new ItemToolHoe(MaterialHandler.Tools.Sirium, "sirium_hoe");
	public static ItemToolHoe DEMONIC_HOE = new ItemToolHoe(MaterialHandler.Tools.Demonic, "demonic_hoe");
	public static ItemToolHoe STEEL_HOE = new ItemToolHoe(MaterialHandler.Tools.Steel, "steel_hoe");
	public static ItemToolHoe BRONZE_HOE = new ItemToolHoe(MaterialHandler.Tools.Bronze, "bronze_hoe");
	public static ItemToolHoe SILVER_HOE = new ItemToolHoe(MaterialHandler.Tools.Silver, "silver_hoe");
	public static ItemToolPickaxe TITANIUM_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Titanium, "titanium_pickaxe", null, -1);
	public static ItemToolPickaxe VIBRANIUM_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Vibranium, "vibranium_pickaxe", null, -1);
	public static ItemToolPickaxe ADAMANTIUM_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Adamantium, "adamantium_pickaxe", null, -1);
	public static ItemToolPickaxe SIRIUM_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Sirium, "sirium_pickaxe", null, -1);
	public static ItemToolPickaxe DEMONIC_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Demonic, "demonic_pickaxe", null, -1);
	public static ItemToolPickaxe STEEL_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Steel, "steel_pickaxe", null, -1);
	public static ItemToolPickaxe BRONZE_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Bronze, "bronze_pickaxe", null, -1);
	public static ItemToolPickaxe SILVER_PICKAXE = new ItemToolPickaxe(MaterialHandler.Tools.Silver, "silver_pickaxe", null, -1);
	public static ItemToolShovel TITANIUM_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Titanium, "titanium_shovel", null, -1);
	public static ItemToolShovel VIBRANIUM_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Vibranium, "vibranium_shovel", null, -1);
	public static ItemToolShovel ADAMANTIUM_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Adamantium, "adamantium_shovel", null, -1);
	public static ItemToolShovel SIRIUM_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Sirium, "sirium_shovel", null, -1);
	public static ItemToolShovel DEMONIC_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Demonic, "demonic_shovel", null, -1);
	public static ItemToolShovel STEEL_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Steel, "steel_shovel", null, -1);
	public static ItemToolShovel BRONZE_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Bronze, "bronze_shovel", null, -1);
	public static ItemToolShovel SILVER_SHOVEL = new ItemToolShovel(MaterialHandler.Tools.Silver, "silver_shovel", null, -1);
	public static ItemToolSword TITANIUM_SWORD = new ItemToolSword(MaterialHandler.Tools.Titanium, "titanium_sword", null, -1);
	public static ItemToolSword VIBRANIUM_SWORD = new ItemToolSword(MaterialHandler.Tools.Vibranium, "vibranium_sword", null, -1);
	public static ItemToolSword ADAMANTIUM_SWORD = new ItemToolSword(MaterialHandler.Tools.Adamantium, "adamantium_sword", null, -1);
	public static ItemToolSword SIRIUM_SWORD = new ItemToolSword(MaterialHandler.Tools.Sirium, "sirium_sword", null, -1);
	public static ItemToolSword DEMONIC_SWORD = new ItemToolSword(MaterialHandler.Tools.Demonic, "demonic_sword", null, -1);
	public static ItemToolSword STEEL_SWORD = new ItemToolSword(MaterialHandler.Tools.Steel, "steel_sword", null, -1);
	public static ItemToolSword BRONZE_SWORD = new ItemToolSword(MaterialHandler.Tools.Bronze, "bronze_sword", null, -1);
	public static ItemToolSword SILVER_SWORD = new ItemToolSword(MaterialHandler.Tools.Silver, "silver_sword", null, -1);
	public static ItemToolAoE TITANIUM_HAMMER = new ItemToolAoE("titanium_hammer", MaterialHandler.Tools.Titanium_AoE);
	public static ItemToolAoE VIBRANIUM_HAMMER = new ItemToolAoE("vibranium_hammer", MaterialHandler.Tools.Vibranium_AoE);
	public static ItemToolAoE ADAMANTIUM_HAMMER = new ItemToolAoE("adamantium_hammer", MaterialHandler.Tools.Adamantium_AoE);
	public static ItemToolAoE SIRIUM_HAMMER = new ItemToolAoE("sirium_hammer", MaterialHandler.Tools.Sirium_AoE);
	public static ItemToolAoE DEMONIC_HAMMER = new ItemToolAoE("demonic_hammer", MaterialHandler.Tools.Demonic_AoE);
	public static ItemToolAoE STEEL_HAMMER = new ItemToolAoE("steel_hammer", MaterialHandler.Tools.Steel_AoE);
	public static ItemToolAoE BRONZE_HAMMER = new ItemToolAoE("bronze_hammer", MaterialHandler.Tools.Bronze_AoE);
	public static ItemToolAoE SILVER_HAMMER = new ItemToolAoE("silver_hammer", MaterialHandler.Tools.Silver_AoE);
	public static ItemToolAoE TITANIUM_EXCAVATOR = new ItemToolAoE("titanium_excavator", MaterialHandler.Tools.Titanium_AoE, true);
	public static ItemToolAoE VIBRANIUM_EXCAVATOR = new ItemToolAoE("vibranium_excavator", MaterialHandler.Tools.Vibranium_AoE, true);
	public static ItemToolAoE ADAMANTIUM_EXCAVATOR = new ItemToolAoE("adamantium_excavator", MaterialHandler.Tools.Adamantium_AoE, true);
	public static ItemToolAoE SIRIUM_EXCAVATOR = new ItemToolAoE("sirium_excavator", MaterialHandler.Tools.Sirium_AoE, true);
	public static ItemToolAoE DEMONIC_EXCAVATOR = new ItemToolAoE("demonic_excavator", MaterialHandler.Tools.Demonic_AoE, true);
	public static ItemToolAoE STEEL_EXCAVATOR = new ItemToolAoE("steel_excavator", MaterialHandler.Tools.Steel_AoE, true);
	public static ItemToolAoE BRONZE_EXCAVATOR = new ItemToolAoE("bronze_excavator", MaterialHandler.Tools.Bronze_AoE, true);
	public static ItemToolAoE SILVER_EXCAVATOR = new ItemToolAoE("silver_excavator", MaterialHandler.Tools.Silver_AoE, true);
	public static ItemToolHammer HAMMER = new ItemToolHammer(NaberiusConfig.HAMMER_DURABILITY);
		
	public static void init(){

		ITEMS.add(INGOT);
		ITEMS.add(CORE);
		ITEMS.add(NUGGET);
		ITEMS.add(PLATE);
		ITEMS.add(DEMON_FLESH);
		ITEMS.add(MANUAL);
		ITEMS.add(DEMONIC_STONE);
		ITEMS.add(CLEANSED_DEMON_PORTER);
		ITEMS.add(CORRUPTED_DEMON_PORTER);
		ITEMS.add(BACKPACK);
		ITEMS.add(HOLY_WATER);
		ITEMS.add(DEMON_PEARL);
		ITEMS.add(DEMON_EYE);
		ITEMS.add(TITANIUM_AXE);
		ITEMS.add(VIBRANIUM_AXE);
		ITEMS.add(ADAMANTIUM_AXE);
		ITEMS.add(SIRIUM_AXE);
		ITEMS.add(DEMONIC_AXE);
		ITEMS.add(STEEL_AXE);
		ITEMS.add(BRONZE_AXE);
		ITEMS.add(SILVER_AXE);
		ITEMS.add(TITANIUM_HOE);
		ITEMS.add(VIBRANIUM_HOE);
		ITEMS.add(ADAMANTIUM_HOE);
		ITEMS.add(SIRIUM_HOE);
		ITEMS.add(DEMONIC_HOE);
		ITEMS.add(STEEL_HOE);
		ITEMS.add(BRONZE_HOE);
		ITEMS.add(SILVER_HOE);
		ITEMS.add(TITANIUM_PICKAXE);
		ITEMS.add(VIBRANIUM_PICKAXE);
		ITEMS.add(ADAMANTIUM_PICKAXE);
		ITEMS.add(SIRIUM_PICKAXE);
		ITEMS.add(DEMONIC_PICKAXE);
		ITEMS.add(STEEL_PICKAXE);
		ITEMS.add(BRONZE_PICKAXE);
		ITEMS.add(SILVER_PICKAXE);
		ITEMS.add(TITANIUM_SHOVEL);
		ITEMS.add(VIBRANIUM_SHOVEL);
		ITEMS.add(ADAMANTIUM_SHOVEL);
		ITEMS.add(SIRIUM_SHOVEL);
		ITEMS.add(DEMONIC_SHOVEL);
		ITEMS.add(STEEL_SHOVEL);
		ITEMS.add(BRONZE_SHOVEL);
		ITEMS.add(SILVER_SHOVEL);
		ITEMS.add(TITANIUM_SWORD);
		ITEMS.add(VIBRANIUM_SWORD);
		ITEMS.add(ADAMANTIUM_SWORD);
		ITEMS.add(SIRIUM_SWORD);
		ITEMS.add(DEMONIC_SWORD);
		ITEMS.add(STEEL_SWORD);
		ITEMS.add(BRONZE_SWORD);
		ITEMS.add(SILVER_SWORD);
		ITEMS.add(TITANIUM_HAMMER);
		ITEMS.add(VIBRANIUM_HAMMER);
		ITEMS.add(ADAMANTIUM_HAMMER);
		ITEMS.add(SIRIUM_HAMMER);
		ITEMS.add(DEMONIC_HAMMER);
		ITEMS.add(STEEL_HAMMER);
		ITEMS.add(BRONZE_HAMMER);
		ITEMS.add(SILVER_HAMMER);
		ITEMS.add(TITANIUM_EXCAVATOR);
		ITEMS.add(VIBRANIUM_EXCAVATOR);
		ITEMS.add(ADAMANTIUM_EXCAVATOR);
		ITEMS.add(SIRIUM_EXCAVATOR);
		ITEMS.add(DEMONIC_EXCAVATOR);
		ITEMS.add(STEEL_EXCAVATOR);
		ITEMS.add(BRONZE_EXCAVATOR);
		ITEMS.add(SILVER_EXCAVATOR);
		ITEMS.add(HAMMER);
		ITEMS.add(ItemBronzeArmor.bronze_helmet);
		ITEMS.add(ItemBronzeArmor.bronze_chest);
		ITEMS.add(ItemBronzeArmor.bronze_leggs);
		ITEMS.add(ItemBronzeArmor.bronze_boots);
		ITEMS.add(ItemSteelArmor.steel_helmet);
		ITEMS.add(ItemSteelArmor.steel_chest);
		ITEMS.add(ItemSteelArmor.steel_leggs);
		ITEMS.add(ItemSteelArmor.steel_boots);
		ITEMS.add(ItemAdamantiumArmor.adamantium_helmet);
		ITEMS.add(ItemAdamantiumArmor.adamantium_chest);
		ITEMS.add(ItemAdamantiumArmor.adamantium_leggs);
		ITEMS.add(ItemAdamantiumArmor.adamantium_boots);
		ITEMS.add(ItemSiriumArmor.sirium_helmet);
		ITEMS.add(ItemSiriumArmor.sirium_chest);
		ITEMS.add(ItemSiriumArmor.sirium_leggs);
		ITEMS.add(ItemSiriumArmor.sirium_boots);
		ITEMS.add(ItemDemonicArmor.demonic_helmet);
		ITEMS.add(ItemDemonicArmor.demonic_chest);
		ITEMS.add(ItemDemonicArmor.demonic_leggs);
		ITEMS.add(ItemDemonicArmor.demonic_boots);
		
		for (Item item : ITEMS){
			GameRegistry.register(item);
		}
				
	}
	
}
